import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {canonicalArcs,putArc,removeArc,rowArcSegments} from '../src/lib/arcEditing.js';
import {replaceText} from '../src/correction/model.js';
import {tieLinksForDocument,buildPitchPlan} from '../src/lib/musicStructure.js';
import {FIXTURE_SKIP, optionalLocalFixture} from './helpers/local-fixtures.mjs';
const note=(id,degree=1)=>({id,degree,octave:0,accidental:null,annotation:{durationTicks:24,dotted:false,measureEnd:false,tieToNext:false}});
const fixture=()=>({meter:{beats:4,beatUnit:4},rows:[{page:0,line:0,text:'1 1 2 3',notes:[note('a'),note('b'),note('c',2),note('d',3)]},{page:0,line:1,text:'4 5',notes:[note('e',4),note('f',5)]},{page:1,line:0,text:'6 7',notes:[note('g',6),note('h',7)]}],music:{arcs:[],measures:[],tuplets:[]}});
test('legacy tie markers convert to arcs and deleted arcs do not resurrect',{skip:FIXTURE_SKIP},async()=>{const raw=JSON.parse(await readFile(optionalLocalFixture('legacy-public/song/corrected-draft.json'),'utf8')).document;const count=raw.rows.flatMap(r=>r.notes).filter(n=>n.annotation.tieToNext).length;const doc=canonicalArcs(raw);assert.equal(doc.music.arcs.length,count);assert.ok(doc.rows.flatMap(r=>r.notes).every(n=>!n.annotation.tieToNext));const deleted=removeArc(doc,doc.music.arcs[0].id);assert.equal(canonicalArcs(JSON.parse(JSON.stringify(deleted))).music.arcs.length,count-1);});
test('same pitch merges playback; different and long arcs do not',()=>{let d=putArc(fixture(),{id:'same',fromNoteId:'a',toNoteId:'b'});assert.equal(tieLinksForDocument(d)[0],true);d=putArc(d,{id:'different',fromNoteId:'b',toNoteId:'c'});assert.equal(tieLinksForDocument(d)[1],false);d=putArc(d,{id:'long',fromNoteId:'c',toNoteId:'g'});assert.equal(d.music.arcs.find(a=>a.id==='long').effectiveType,'slur');assert.equal(putArc(d,{id:'reverse',fromNoteId:'c',toNoteId:'a'}).music.arcs.find(a=>a.id==='reverse').fromNoteId,'a');});
test('cross-page arc is visible through intermediate rows with layering',()=>{let d=putArc(fixture(),{id:'long',fromNoteId:'a',toNoteId:'h'});d=putArc(d,{id:'short',fromNoteId:'a',toNoteId:'c'});assert.equal(rowArcSegments(d,1)[0].typeSegment,'through');assert.equal(rowArcSegments(d,2)[0].typeSegment,'incoming');const first=rowArcSegments(d,0);assert.ok(first.find(a=>a.id==='long').level>first.find(a=>a.id==='short').level);});
test('text insertion retains unchanged IDs and arcs, not new-note duration',()=>{const d=putArc(fixture(),{id:'a',fromNoteId:'c',toNoteId:'h'});const r=replaceText(d,0,'1 1 2 4 3');assert.equal(r.document.rows[0].notes[2].id,'c');assert.equal(r.document.rows[0].notes[3].annotation.durationTicks,null);assert.equal(r.document.music.arcs[0].toNoteId,'h');assert.equal(r.pending,0);});
test('same-count replacement invalidates affected incoming/outgoing endpoints only',()=>{let d=putArc(fixture(),{id:'affected',fromNoteId:'c',toNoteId:'h'});d=putArc(d,{id:'safe',fromNoteId:'e',toNoteId:'g'});const r=replaceText(d,0,'1 1 4 3');assert.equal(r.document.music.arcs.length,1);assert.equal(r.document.music.arcs[0].id,'safe');assert.equal(r.document.music.pendingArcs[0].id,'affected');assert.equal(canonicalArcs(JSON.parse(JSON.stringify(r.document))).music.pendingArcs.length,1);const repaired=putArc(r.document,{id:'affected',fromNoteId:r.document.rows[0].notes[2].id,toNoteId:'h'});assert.equal(repaired.music.pendingArcs.length,0);});

test('explicit reconnection clears only that seam diagnostic',()=>{const d=fixture();d.structureDiagnostics=[{code:'SEAM_RELATION_CHANGED',fromNoteId:'a',toNoteId:'b'},{code:'SEAM_RELATION_CHANGED',fromNoteId:'d',toNoteId:'e'}];const r=putArc(d,{fromNoteId:'a',toNoteId:'b'});assert.equal(r.structureDiagnostics.length,1);assert.equal(tieLinksForDocument(r)[0],true);});

test('arc edits retain the song key and octave across normalization',()=>{const d=canonicalArcs(fixture(),{key:'E',octave:3});const before=buildPitchPlan(d).map(p=>p.midi);const changed=putArc(d,{id:'new',fromNoteId:'a',toNoteId:'b'});assert.deepEqual(buildPitchPlan(changed).map(p=>p.midi),before);assert.equal(changed.key,'E');assert.equal(changed.octave,3);});

test('octave marks: text input accepts one or two marks and rejects three',()=>{const d=fixture();assert.equal(replaceText(d,0,"1'' 1 2 3").document.rows[0].notes[0].octave,2,'双高音');assert.equal(replaceText(d,0,'..1 1 2 3').document.rows[0].notes[0].octave,-2,'双低音');assert.equal(replaceText(d,0,"1' 1 2 3").document.rows[0].notes[0].octave,1,'单高音仍可用');assert.throws(()=>replaceText(d,0,"1''' 1 2 3"),/最多两个/);});
