import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
export const hash=b=>createHash('sha256').update(b).digest('hex');
export const safeId=id=>{if(!/^[a-zA-Z0-9_-]{1,160}$/.test(id))throw Object.assign(Error('标识无效'),{status:400});return id};
export const json=async(file,fallback)=>{try{return JSON.parse(await fs.readFile(file,'utf8'))}catch(e){if(e.code==='ENOENT')return fallback;throw e}};
export async function atomic(file,value){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=file+'.'+randomUUID()+'.tmp';const h=await fs.open(tmp,'wx');try{await h.writeFile(typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value,null,2));await h.sync()}finally{await h.close()}await fs.rename(tmp,file)}
export class DataStore{
 constructor(root){this.root=path.resolve(root);this.queue=Promise.resolve();this.failed=false}
 file(rel){const f=path.resolve(this.root,rel);if(!f.startsWith(this.root+path.sep))throw Error('路径越界');return f}
 serial(fn){const run=this.queue.then(()=>{if(this.failed)throw Error('上次保存未完成，请重启乐北斗恢复数据后继续');return fn()});this.queue=run.catch(()=>{});return run}
 async init(){await fs.mkdir(this.root,{recursive:true});await this.recover();if(!await json(this.file('library.json'),null))await atomic(this.file('library.json'),{schemaVersion:1,revision:0,songIds:[]});const value=await json(this.file('library.json'));if(value.schemaVersion!==1)throw Error('数据版本不兼容，请使用匹配的乐北斗版本');await fs.mkdir(this.file('logs'),{recursive:true});for(const id of value.songIds){const dir=this.file('songs/'+safeId(id)+'/recognition');for(const name of await fs.readdir(dir).catch(e=>{if(e.code==='ENOENT')return [];throw e})){if(!name.endsWith('.json'))continue;const file=path.join(dir,name),record=await json(file);if(record.status==='running')await atomic(file,{...record,status:'interrupted',finishedAt:Date.now()})}}}
 async recover(){const pending=await json(this.file('_transaction/manifest.json'),null);if(!pending)return;for(const rel of pending.files){const source=this.file('_transaction/files/'+rel);const bytes=await fs.readFile(source);await atomic(this.file(rel),bytes.toString('utf8'))}await this.clearTransaction()}
 async clearTransaction(){const target=this.file('_transaction');if(path.dirname(target)!==this.root)throw Error('路径越界');await fs.rm(target,{recursive:true,force:true})}
 async transaction(changes){if(!changes.size)return;const id=Date.now()+'-'+randomUUID();for(const [rel,value] of changes){await atomic(this.file('_transaction/files/'+rel),value);try{const previous=await fs.readFile(this.file(rel));await atomic(this.file('backups/'+id+'/'+rel),previous.toString('utf8'))}catch(e){if(e.code!=='ENOENT')throw e}}await atomic(this.file('_transaction/manifest.json'),{schemaVersion:1,files:[...changes.keys()]});try{await this.recover()}catch(e){this.failed=true;throw e}}
 async state(){return this.serial(async()=>{const index=await json(this.file('library.json'));const songs=await Promise.all(index.songIds.map(id=>json(this.file('songs/'+safeId(id)+'/song.json'))));return {schemaVersion:1,revision:index.revision,songs,settings:await json(this.file('settings.json'),{})}})}
 async materialize(value,songId){if(typeof value==='string'&&value.startsWith('data:image/')){const m=/^data:image\/(png|jpeg|webp|gif);base64,([\s\S]+)$/.exec(value);if(!m)throw Object.assign(Error('图片格式无效'),{status:400});const bytes=Buffer.from(m[2],'base64');if(bytes.length>30*1024*1024)throw Error('图片超过 30 MB');const rel='songs/'+safeId(songId)+'/images/'+hash(bytes)+'.'+(m[1]==='jpeg'?'jpg':m[1]);await fs.mkdir(path.dirname(this.file(rel)),{recursive:true});const existing=await fs.readFile(this.file(rel)).catch(e=>{if(e.code==='ENOENT')return null;throw e});if(!existing||hash(existing)!==hash(bytes))await atomic(this.file(rel),bytes);return '/media/'+rel}
 if(Array.isArray(value))return Promise.all(value.map(v=>this.materialize(v,songId)));
 if(value&&typeof value==='object'){const output={};for(const [k,v] of Object.entries(value)){if(['apiKey','api_key','authorization','encryptedApiKey','CryptoKey'].includes(k))continue;output[k]=await this.materialize(v,songId)}return output}return value}
 async save(value,expected){return this.serial(async()=>{const index=await json(this.file('library.json'));if(expected!==index.revision)throw Object.assign(Error('其他窗口已更新曲库，请刷新后重新操作；当前修改尚未保存'),{status:409});if(!Array.isArray(value.songs))throw Object.assign(Error('曲库格式无效'),{status:400});const changes=new Map(),ids=[];for(const song of value.songs){safeId(song.id);if(ids.includes(song.id))throw Error('歌曲标识重复');ids.push(song.id);const next=await this.materialize(song,song.id);const rel='songs/'+song.id+'/song.json',old=await json(this.file(rel),null);if(JSON.stringify(old)!==JSON.stringify(next))changes.set(rel,next)}
 const settings={...value.settings};for(const key of ['apiKey','api_key','authorization','encryptedApiKey','CryptoKey','demoResult','recognitionMode'])delete settings[key];if(JSON.stringify(await json(this.file('settings.json'),{}))!==JSON.stringify(settings))changes.set('settings.json',settings);if(!changes.size&&JSON.stringify(ids)===JSON.stringify(index.songIds))return {revision:index.revision};changes.set('library.json',{schemaVersion:1,revision:index.revision+1,songIds:ids});await this.transaction(changes);return {revision:index.revision+1}})}
 async readDocument(rel){return this.serial(async()=>await json(this.file(rel),{schemaVersion:1,revision:0,value:null}))}
 async writeDocument(rel,value,revision){return this.serial(async()=>{const old=await json(this.file(rel),{revision:0});if(revision!==old.revision)throw Object.assign(Error('其他窗口已更新此数据，请刷新后再操作'),{status:409});const next={schemaVersion:1,revision:revision+1,value};await this.transaction(new Map([[rel,next]]));return {revision:next.revision}})}
 async archive(songId,record,existing){return this.serial(async()=>{safeId(songId);const value=await this.materialize(record,songId);const rel=existing||'songs/'+songId+'/recognition/'+new Date().toISOString().replace(/[:.]/g,'-')+'-'+randomUUID()+'.json';await atomic(this.file(rel),{schemaVersion:1,...value});return {file:rel}})}
}

