import {cropPolygonStyle,editingCropRect,adjustCropEdge} from '../cropGeometry.js';
import {inferredNormal,normalOptions,defaultNormal,stepNormal} from '../lib/notationFeatures.js';
import {compactDocument,readDraft,writeDraft} from './draftStore.js';
import {canonicalArcs,putArc,removeArc,locateNote,setMeterChange} from '../lib/arcEditing.js';
import React,{useState,useEffect,useRef,useLayoutEffect} from 'react';
import {createDocument,move,edit,replaceText,measures,label,durations,names,fractions,deleteRow} from './model.js';
import {EngravedRow} from './EngravedRow.jsx';
import {SourceRowTargets} from './SourceRowTargets.jsx';
import {CropPreview} from './CropPreview.jsx';
import {MeterFields} from './MeterFields.jsx';
import {manualCrop,reconcileCropDraft} from '../cropGeometry.js';
import {beatPositions,cropRect,scoreSize} from './layoutRules.js';
export function App(){
const [doc,setDoc]=useState(null),[initial,setInitial]=useState(null),[cursor,setCursor]=useState({row:2,note:0}),[overview,setOverview]=useState(false),[viewPage,setViewPage]=useState(0),[loaded,setLoaded]=useState(0),[modal,setModal]=useState(null),[draft,setDraft]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[saveState,setSaveState]=useState('已保存到本机'),[confirmDeleteRow,setConfirmDeleteRow]=useState(false);
const [notationSize,setNotationSize]=useState(24);
const [arcDraft,setArcDraft]=useState(null);const arcReturn=useRef(null);const draftQueue=useRef(Promise.resolve());
const commit=next=>setDoc(next);
const cancelArc=()=>{if(arcReturn.current)setCursor(arcReturn.current);setArcDraft(null);focus()};
const confirmArc=()=>{if(!arcDraft)return doc;try{const next=putArc(doc,arcDraft);commit(next);setArcDraft(null);focus();return next;}catch(e){setToast(e.message);return doc;}};

const selectArc=a=>{if(arcDraft){focus();return;}arcReturn.current={...cursor};setArcDraft({id:a.id,fromNoteId:a.fromNoteId,toNoteId:a.toNoteId,number:a.number??null,normal:a.normal??null});const end=locateNote(doc,a.toNoteId);if(end)setCursor(end);focus()};
const currentArcs=()=>{const id=doc.rows[cursor.row]?.notes[cursor.note]?.id;if(!id)return[];return doc.music.arcs.filter(a=>a.fromNoteId===id&&locateNote(doc,a.toNoteId));};
const toggleArc=()=>{if(arcDraft)return;const arcs=currentArcs();if(arcs.length){commit(arcs.reduce((next,a)=>removeArc(next,a.id),doc));focus();return;}beginArc();};
const beginArc=()=>{if(arcDraft)return;const all=doc.rows.flatMap(r=>r.notes),n=doc.rows[cursor.row].notes[cursor.note];if(!n.degree){setToast('请选择连接的起始音符');return;}const existing=doc.music.arcs.find(a=>a.fromNoteId===n.id&&locateNote(doc,a.toNoteId));if(existing){selectArc(existing);return;}const end=all.slice(all.indexOf(n)+1).find(n=>n.degree);if(!end){setToast('后面没有可连接的音符');return;}arcReturn.current={...cursor};setArcDraft({fromNoteId:n.id,toNoteId:end.id,number:null,normal:null});setCursor(locateNote(doc,end.id));focus()};
const moveArc=d=>{let target=move(doc.rows,cursor,d);const all=doc.rows.flatMap(r=>r.notes),start=all.findIndex(n=>n.id===arcDraft.fromNoteId);let n=doc.rows[target.row].notes[target.note];if(!n)return;if(!n.degree){const step=d==='left'?-1:1;let index=all.indexOf(n);do{index+=step;n=all[index]}while(n&&!n.degree);if(!n)return;target=locateNote(doc,n.id);}if(all.indexOf(n)<=start)return;setArcDraft(a=>({...a,toNoteId:n.id}));setCursor(target);focus()};
const deleteArc=()=>{if(!arcDraft?.id){cancelArc();return;}commit(removeArc(doc,arcDraft.id));setArcDraft(null);focus()};
const sourceSelection=useRef(null);
const editor=useRef(),source=useRef(),imgs=useRef([]),rowsArea=useRef(),overviewRows=useRef([]),cooldown=useRef(0),wheelDelta=useRef(0);
const [song,setSong]=useState(null);
useEffect(()=>{const receive=async e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='correction-init'){const value=e.data;setSong(value.song);setInitial(compactDocument(value.document));let saved;try{saved=await readDraft(value.song.id,value.document)}catch{setSaveState('无法读取本地编辑草稿，请检查数据目录')}setDoc(canonicalArcs(saved?.document||compactDocument(value.document),{key:value.song.key,octave:value.song.octave,bpm:value.song.bpm}));setCursor(saved?.cursor||value.cursor||{row:0,note:0})}if(e.data?.type==='correction-error')setSaveState(e.data.message)};window.addEventListener('message',receive);parent.postMessage({type:'correction-ready'},location.origin);return()=>window.removeEventListener('message',receive)},[]);
useEffect(()=>{if(!doc||!song)return;let active=true;const timer=setTimeout(()=>{draftQueue.current=draftQueue.current.catch(()=>{}).then(()=>writeDraft(song.id,initial,doc,arcDraft?arcReturn.current:cursor));draftQueue.current.then(()=>{if(active)setSaveState('已保存到本机')},()=>{if(active)setSaveState('编辑草稿保存失败，请检查数据目录后重试')});},200);return()=>{active=false;clearTimeout(timer)}},[doc,cursor,song,initial,Boolean(arcDraft)]);
const finish=()=>{if(arcDraft)return;const finalDoc=doc;setSaveState('正在保存…');parent.postMessage({type:'correction-save',document:finalDoc,cursor},location.origin)};
useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(id)}},[toast]);
const focus=()=>requestAnimationFrame(()=>editor.current?.focus({preventScroll:true}));
useEffect(()=>{if(doc)focus()},[Boolean(doc)]);
useLayoutEffect(()=>{if(!doc||!editor.current)return;const el=editor.current;const resize=()=>setNotationSize(scoreSize(el.clientWidth,el.clientHeight));const ob=new ResizeObserver(resize);ob.observe(el);resize();return()=>ob.disconnect()},[Boolean(doc)]);
const select=(row,note=0)=>{if(arcDraft){const target=doc.rows[row]?.notes[note],all=doc.rows.flatMap(r=>r.notes);if(!target||!target.degree||all.indexOf(target)<=all.findIndex(n=>n.id===arcDraft.fromNoteId)){setToast('请选择起点之后的音符作为终点');focus();return;}setArcDraft(a=>({...a,toNoteId:target.id}));}sourceSelection.current=null;setCursor({row,note});focus()};
const navigate=d=>{sourceSelection.current=null;setCursor(c=>move(doc.rows,c,d));focus()};
const center=()=>{if(!doc)return;const row=doc.rows[cursor.row],img=imgs.current[row.page],sc=source.current;if(!img||!sc)return;sc.scrollTop+=img.getBoundingClientRect().top-sc.getBoundingClientRect().top+img.clientHeight*((cropRect(row.crop,img.naturalWidth,img.naturalHeight).y)+(cropRect(row.crop,img.naturalWidth,img.naturalHeight).height)/2)-sc.clientHeight/2};
useEffect(()=>{if(sourceSelection.current===cursor.row)return;center()},[cursor.row,loaded]);
useLayoutEffect(()=>{if(!rowsArea.current)return;if(!overview){rowsArea.current.scrollTop=0;return}const el=overviewRows.current[cursor.row];if(el)rowsArea.current.scrollTop=el.offsetTop-16},[overview]);
useEffect(()=>{const el=rowsArea.current;if(!el||overview||!doc)return;const fn=e=>{if(e.target.closest('.overflowing')||e.ctrlKey||Math.abs(e.deltaX)>Math.abs(e.deltaY))return;e.preventDefault();wheelDelta.current+=e.deltaY;if(Date.now()-cooldown.current<170||Math.abs(wheelDelta.current)<24)return;if(arcDraft){e.stopPropagation();return;}const d=wheelDelta.current>0?'down':'up';wheelDelta.current=0;cooldown.current=Date.now();sourceSelection.current=null;setCursor(c=>move(doc.rows,c,d));focus()};el.addEventListener('wheel',fn,{passive:false});return()=>el.removeEventListener('wheel',fn)},[overview,doc,arcDraft]);
const update=a=>{if(arcDraft||!doc.rows[cursor.row]?.notes[cursor.note])return;if(a==='meterChange'){const m=measures(doc).find(m=>m.noteIds.includes(doc.rows[cursor.row].notes[cursor.note].id));if(m)commit(setMeterChange(doc,m.startNoteId,doc.music.meterChanges?.some(c=>c.noteId===m.startNoteId)?null:m.meter));focus();return;}if(a==='tieToNext'){toggleArc();return;}commit(edit(doc,cursor,a));focus()};
const openText=()=>{if(arcDraft)return;setDraft(doc.rows[cursor.row].notes.map(n=>label(n)+(n.annotation.measureEnd?' |':'')).join(' '));setError('');setModal('text')};
const close=()=>{setModal(null);setError('');setConfirmDeleteRow(false);focus()};
// 删除本行：行消失 → 它的裁切区域随之消失（左栏原图高亮与行目标都由 doc.rows 派生）。
const removeCurrentRow=()=>{const result=deleteRow(doc,cursor.row);if(result.document===doc&&!result.cursor){setToast('没有可删除的行');return;}commit(result.document);setConfirmDeleteRow(false);setModal(null);if(!result.cursor){setToast('已删除本页最后一行；保存并返回训练后该页为空');focus();return;}setCursor(result.cursor);setToast('已删除该行；保存并返回训练后生效');focus()};
const keys=e=>{if(modal||e.altKey||e.isComposing)return;
 // 连音控件不抢焦点，但按键仍要交给编辑器处理；其余输入控件保持原有屏蔽。
 if(e.target.closest('input,textarea,select')&&!e.target.closest('.connection-normal'))return;
 if(e.ctrlKey||e.metaKey)return;
 const dirs={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};
 if(arcDraft){
  // 占几个同类音的时长可见时，上下键改为调这个值（其余方向键仍移动连接终点）。
  if(normalFieldVisible&&(e.key==='ArrowUp'||e.key==='ArrowDown')){e.preventDefault();changeConnection(arcDraft.number,stepNormal(arcDraft.number,selectedMeasure?.meter,connectionNormal,e.key==='ArrowUp'?'up':'down'));return;}
  if(dirs[e.key]){e.preventDefault();moveArc(dirs[e.key]);return;}
  if(['Enter','Escape','Delete','Backspace'].includes(e.key)){e.preventDefault();if(e.key==='Enter')confirmArc();else if(e.key==='Escape')cancelArc();else deleteArc();return;}
  // 数字键直接选连音数：2–9 为几连音，1 回到普通连接。
  if(/^[1-9]$/.test(e.key)){e.preventDefault();if(!e.repeat)changeConnection(e.key==='1'?0:Number(e.key));return;}
  if(/^[qwedrf]$/i.test(e.key))e.preventDefault();
  return;
 }
 if(dirs[e.key]){e.preventDefault();if(!overview||['ArrowUp','ArrowDown'].includes(e.key))navigate(dirs[e.key]);return;}if(overview){if(e.key==='Enter'||e.key==='Escape'){e.preventDefault();setOverview(false)}return;}
 const k=e.key.toLowerCase(),map={q:'dotted',w:'tieToNext',e:'measureEnd',d:'meterChange',r:'raise',f:'lower'};if(map[k]||/^[1-5]$/.test(k)){e.preventDefault();if(!e.repeat)update(map[k]||durations[Number(k)-1])}};

if(!doc)return <div className="loading">{error||'正在载入《沙龙》…'}</div>;
const current=doc.rows[cursor.row]||{notes:[],page:0,line:0,crop:null},rowEmpty=!current.notes.length,note=current.notes[cursor.note],annotation=note?.annotation,connectionActive=!!arcDraft||currentArcs().length>0;
const cropImage=imgs.current[current.page],box=editingCropRect(current.crop,cropImage?.naturalWidth||1,cropImage?.naturalHeight||song.images[current.page]?.ratio||1);
const allMeasures=measures(doc),offsets=[];let count=0;doc.rows.forEach(r=>{offsets.push(count);count+=r.notes.length});
const selectedMeasure=allMeasures.find(m=>m.noteIds.includes(note?.id)),meterMark=doc.music.meterChanges?.find(c=>c.noteId===selectedMeasure?.startNoteId),selectedConnection=arcDraft||currentArcs()[0];
const connectionNumber=selectedConnection?.number??0;
// 占几个同类音：显式值优先，其次推导值，最后按常见写法兜底——永远给出一个合法值，不留给引擎判错。
const connectionNormal=connectionNumber?(selectedConnection?.normal??inferredNormal(connectionNumber,selectedMeasure?.meter)??defaultNormal(connectionNumber,selectedMeasure?.meter)):null;
const normalUnknown=connectionNumber&&!connectionNormal;
const normalUnusual=Boolean(connectionNumber&&connectionNormal)&&!normalOptions(connectionNumber,selectedMeasure?.meter).includes(connectionNormal);
// 只要是连音就始终显示「占几个同类音的时长」：默认值已经合法，↑↓ 可在合法候选内改。
const normalFieldVisible=Boolean(connectionNumber);
// 草稿的 number 先落地（未确认时也记着"第几连音"），数字键、按钮、↑↓ 都改它。
const changeConnection=(number,normal=null)=>{const value={...selectedConnection,number:number||null,normal:number?(normal??defaultNormal(number,selectedMeasure?.meter)):null};if(arcDraft)setArcDraft(value);else commit(putArc(doc,value))};
const arcLocation=id=>{const p=locateNote(doc,id);return p?'第 '+(doc.rows[p.row].page+1)+' 页 · 第 '+(doc.rows[p.row].line+1)+' 行 · 第 '+(p.note+1)+' 音':'待确认';};
const beamGroups=beatPositions(doc,allMeasures);
const statusLabels={valid:'满拍',pickup:'弱起',under:'欠拍',over:'超拍',incomplete:'待标注'};
const noteRow=(index,passive=false)=><EngravedRow document={doc} rowIndex={index} editing={!passive} arcDraft={arcDraft} onArcSelect={selectArc} row={doc.rows[index]} offset={offsets[index]} allMeasures={allMeasures} fontSize={notationSize} beamGroups={beamGroups} editAction={index===cursor.row&&!passive&&!arcDraft?openText:null} stableEditing={!overview} active={index===cursor.row?cursor.note:-1} passive={passive} onSelect={n=>select(index,n)} previousTie={index>0&&Boolean(doc.rows[index-1].notes.at(-1)?.annotation.tieToNext)} nextExists={index<doc.rows.length-1}/>;const crop=(band=current.crop)=><CropPreview key={current.page} src={song.images[current.page].src} page={current.page} line={current.line} band={band}/>;
return <div className="app">
<aside className="rail"><span className="vertical-name">{song.title}</span><button aria-label="操作帮助" onClick={()=>setModal('help')}>?</button></aside>
<section className="source-pane"><header><span>原始简谱 <small>第 {viewPage+1} / {song.images.length} 页</small></span><button className="text-button" onClick={center}>定位当前行</button></header><div className="source-scroll" ref={source} onScroll={()=>{const sc=source.current,target=sc.getBoundingClientRect().top+sc.clientHeight/2;let best=0,dist=Infinity;imgs.current.forEach((img,p)=>{if(!img)return;const r=img.getBoundingClientRect(),d=target<r.top?r.top-target:target>r.bottom?target-r.bottom:0;if(d<dist){best=p;dist=d}});setViewPage(best)}}>{song.images.map((image,p)=><figure key={p}><div className="image-surface"><img ref={el=>imgs.current[p]=el} src={image.src} alt={'沙龙原谱第'+(p+1)+'页'} onLoad={()=>setLoaded(x=>x+1)}/>{current.page===p&&!(current.sourceMapping==='page'&&!current.crop)&&imgs.current[p]?.naturalWidth>0&&<div className="source-highlight" style={(()=>{const r=cropRect(current.crop,imgs.current[p].naturalWidth,imgs.current[p].naturalHeight);return {...cropPolygonStyle(current.crop),top:r.y*100+'%',height:r.height*100+'%',left:r.x*100+'%',width:r.width*100+'%'}})()}/>}<SourceRowTargets rows={doc.rows} page={p} image={imgs.current[p]} current={cursor.row} onSelect={row=>{select(row,0);sourceSelection.current=row;}}/></div><figcaption>{p+1} / {song.images.length}</figcaption></figure>)}</div></section>
<main className="editor inline-modes" style={{"--score-scale":notationSize/24,"--score-size":notationSize+"px"}} ref={editor} tabIndex={0} onMouseDown={e=>{if(e.target.closest(".engraved-svg")){e.preventDefault();window.getSelection()?.removeAllRanges();focus()}}} onKeyDown={keys}>
<header className="editor-header"><div><h1>{song.title}</h1><div className="location"><select aria-label="编辑页" value={current.page} onChange={e=>select(Math.max(0,doc.rows.findIndex(r=>r.page===Number(e.target.value))))}>{song.images.map((image,p)=><option key={p} value={p} disabled={!doc.rows.some(r=>r.page===p)}>第 {p+1} 页</option>)}</select><span>/</span><select aria-label="编辑行" value={cursor.row} onChange={e=>select(Number(e.target.value))}>{doc.rows.map((r,i)=>r.page===current.page&&<option key={i} value={i}>第 {r.line+1} 行</option>)}</select><span className="meter-label" aria-label="拍号">{selectedMeasure?.meter.beats??doc.meter.beats}/{selectedMeasure?.meter.beatUnit??doc.meter.beatUnit}</span><button className={"pickup-toggle "+(doc.pickup?"active":"")} aria-pressed={doc.pickup} disabled={!!arcDraft} title="首小节弱起" onClick={()=>{commit({...doc,pickup:!doc.pickup});focus()}}>弱起</button></div></div><button className="primary" disabled={!!arcDraft} onClick={finish}>保存并返回训练</button><div className="mode-switch" role="group" aria-label="工作模式">{[[false,"编辑"],[true,"全曲预览"]].map(([value,text])=><button key={text} aria-pressed={overview===value} disabled={!!arcDraft} onClick={()=>{setOverview(value);focus()}}>{text}</button>)}</div></header>
<section className="crop" data-blocked={rowEmpty?'true':undefined}><div className="crop-caption">{rowEmpty&&<span className="blocked-caption">本行没有音符</span>}{(current.cropNeedsReview||(box.invalid&&current.sourceMapping!=='page'))&&<span>裁切待确认</span>}<button className="text-button" disabled={!!arcDraft} onClick={()=>setModal('crop')}>调整裁切</button></div>{crop()}</section>
<div className={'score-workspace '+(overview?'preview-mode':'edit-mode')} ref={rowsArea} role={overview?'listbox':undefined} aria-label={overview?'全曲音符行':undefined}>
{(overview?doc.rows.map((_,i)=>i):Array.from({length:3},(_,i)=>cursor.row+i)).map(i=>i>=doc.rows.length?<div className="workspace-row context" key={i} aria-hidden="true"/>:<div key={i} ref={el=>overviewRows.current[i]=el} data-row={i} data-blocked={!doc.rows[i].notes.length?'true':undefined} className={'workspace-row '+(i===cursor.row?'current':'context')+(doc.rows[i].notes.length?'':' blocked-row')} role={overview?'option':undefined} aria-selected={overview?i===cursor.row:undefined} onClick={overview?e=>{const hit=e.target.closest('[data-note-index]');if(hit)select(i,Number(hit.dataset.noteIndex));else if(i!==cursor.row)select(i)}:undefined} onDoubleClick={overview?e=>{const hit=e.target.closest('[data-note-index]');if(hit)select(i,Number(hit.dataset.noteIndex));else if(i!==cursor.row)select(i);setOverview(false);focus()}:undefined}>
{noteRow(i,overview)}
{overview&&<span className="preview-location">第 {doc.rows[i].page+1} 页 · 第 {doc.rows[i].line+1} 行</span>}
</div>)}
{overview&&<div className="preview-end-space" aria-hidden="true"/>}
</div>
{!overview&&<>
<section className={'editing-controls '+(arcDraft?'connection-mode':'note-mode')} aria-label={arcDraft?'连接设置':'音符设置'}>
{arcDraft?<div className="connection-panel" onMouseDown={e=>e.preventDefault()}>
 <div className="arc-edit-controls"><span>起点：{arcLocation(arcDraft.fromNoteId)}　终点：{arcLocation(arcDraft.toNoteId)}</span><button tabIndex={-1} aria-label="确认连接" onClick={confirmArc}>确认连接 <kbd>Enter</kbd></button><button tabIndex={-1} aria-label="取消" onClick={cancelArc}>取消 <kbd>Esc</kbd></button>{arcDraft.id&&<button tabIndex={-1} onClick={deleteArc}>删除连接</button>}</div>
 <div className="connection-number"><span>连接</span><span className="connection-numbers" role="group" aria-label="连音类型">{[0,2,3,4,5,6,7,8,9].map(n=><button key={n} tabIndex={-1} className={connectionNumber===n?'active':''} aria-label={n?n+'连音':'普通连接'} aria-pressed={connectionNumber===n} onClick={()=>changeConnection(n)}>{n||'普通'}<kbd>{n||1}</kbd></button>)}</span></div>
 <div className="connection-ratio">{normalFieldVisible&&<label>占几个同类音的时长<input className="connection-normal" aria-label="连音正常数量" type="number" min="1" max="16" tabIndex={-1} value={connectionNormal??''} onKeyDown={e=>{if(['ArrowUp','ArrowDown','Enter','Escape'].includes(e.key))e.preventDefault()}} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=16)changeConnection(connectionNumber,n)}}/><kbd>↑↓</kbd></label>}{normalUnusual&&<span className="connection-hint">当前 {connectionNumber}:{connectionNormal}，已按 n:m 计算</span>}</div>
</div>:rowEmpty?<div className="properties empty-row-hint" data-blocked="true"><p>本行没有音符。</p><p className="hint">用「修改本行音符」补上，或用上方「调整裁切」里的「删除本行」移除该行。</p></div>:<div className="properties"><div className="duration-options">{durations.map((d,i)=><button key={d} className={annotation.durationTicks===d?'active':''} aria-pressed={annotation.durationTicks===d} onClick={()=>update(d)}>{names[i]}<kbd>{i+1}</kbd></button>)}</div><div className="flag-options">{[["dotted","附点","Q"],["tieToNext","连接","W"],["measureEnd","此音后结束小节","E"]].map(([a,t,k])=><button key={a} className={(a==='tieToNext'?connectionActive:annotation[a])?'active':''} aria-pressed={a==='tieToNext'?connectionActive:annotation[a]} onClick={()=>update(a)}>{t}<kbd>{k}</kbd></button>)}<div className="meter-option"><button className={meterMark?'active':''} aria-pressed={!!meterMark} onClick={()=>update('meterChange')}>变拍 <kbd>D</kbd></button>{meterMark&&<MeterFields key={meterMark.noteId} mark={meterMark} onApply={(meter,onlyMeasure)=>commit(setMeterChange(doc,meterMark.noteId,meter,onlyMeasure))}/>}</div></div><div className="octave-options"><span>八度</span><button disabled={note.degree===0||note.octave>=1} onClick={()=>update('raise')}>升八度 <kbd>R</kbd></button><span>{note.degree===0?'休止符':note.octave===1?'高音':note.octave===-1?'低音':'中音'}</span><button disabled={note.degree===0||note.octave<=-1} onClick={()=>update('lower')}>降八度 <kbd>F</kbd></button></div></div>}
{!arcDraft&&!!doc.music.pendingArcs?.length&&<details className="pending-connections"><summary>待确认连接 {doc.music.pendingArcs.length}</summary><div className="pending-list">{doc.music.pendingArcs.map((a,i)=><div key={a.id}><button onClick={()=>{const start=locateNote(doc,a.fromNoteId)||cursor;const notes=doc.rows.flatMap(r=>r.notes),n=doc.rows[start.row]?.notes[start.note],end=notes.slice(notes.indexOf(n)+1).find(n=>n.degree);if(!n?.degree||!end){setToast('请先选择可用的起始音符');return;}selectArc({...a,fromNoteId:n.id,toNoteId:end.id});}}>重设连接 {i+1}</button><button onClick={()=>commit(removeArc(doc,a.id))}>移除待确认项</button></div>)}</div></details>}
</section>{saveState!=='已保存到本机'&&<div className="save-error" role="alert">{saveState}</div>}</>}
</main>
{toast&&<div className="toast" role="status">{toast}</div>}
{modal&&<div className="backdrop" onClick={e=>e.target===e.currentTarget&&close()}><section className={"dialog "+(modal==="text"?"text-dialog":"")} role="dialog" aria-modal="true" aria-labelledby="dialog-title" onKeyDown={e=>{if(e.key==='Escape'){if(confirmDeleteRow){setConfirmDeleteRow(false);return;}close()}if(e.key==='Tab'){const els=[...e.currentTarget.querySelectorAll('button:not(:disabled),input,textarea')];const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><header><h2 id="dialog-title">{modal==='text'?'修改本行音符':modal==='crop'?(confirmDeleteRow?'删除本行？':'调整对应行裁切'):'操作帮助'}</h2><button autoFocus={modal!=='text'} onClick={close} aria-label="关闭">×</button></header>
{modal==='text'?<><p>第 {current.page+1} 页 · 第 {current.line+1} 行</p><div className="text-source-crop">{crop()}</div><textarea autoFocus value={draft} onChange={e=>setDraft(e.target.value)} aria-label="本行简谱文本"/><p className="hint">低音 .1　中音 1　高音 1'　小节线 |</p><p className="hint">此处修改音高与小节线，时值由修正面板控制。保留可确认音符的节奏和连接；新增音符需标注，变化的连接端点待确认。</p>{error&&<p role="alert">{error}</p>}<footer><button onClick={close}>取消</button><button className="primary" onClick={()=>{try{const result=replaceText(doc,cursor.row,draft);commit(result.document);setCursor(c=>({...c,note:Math.min(c.note,result.document.rows[c.row].notes.length-1)}));setToast(result.pending?'端点发生变化，相关连接待确认':result.structural?'已保留可确认的音符，新音符需标注节奏':'本行音符已更新');close()}catch(e){setError(e.message)}}}>应用修改</button></footer></>:modal==='crop'?<>{confirmDeleteRow?<><p>删除第 {current.page+1} 页 · 第 {current.line+1} 行？</p><p className="hint">该行将从乐谱中移除，对应的裁切区域一并消除。尚未保存，可点「取消」保留。</p><footer><button onClick={()=>setConfirmDeleteRow(false)}>取消</button><button className="danger-button" onClick={removeCurrentRow}>确认删除</button></footer></>:<>{crop()}<p className="hint">调整此行在原图中的边缘。</p>{['上','下','左','右'].map((name,edge)=>{const values=[box.y,box.y+box.height,box.x,box.x+box.width];return <label className="range-label" key={edge}>{name}边缘<input aria-label={name+'边缘'} type="range" min={edge===1?box.y+.002:edge===3?box.x+.002:0} max={edge===0?box.y+box.height-.002:edge===2?box.x+box.width-.002:1} step=".001" value={values[edge]} onChange={e=>{const v=Number(e.target.value);commit((()=>{const next=structuredClone(doc),r=next.rows[cursor.row],c=adjustCropEdge(r.crop,edge,v,cropImage?.naturalWidth||1,cropImage?.naturalHeight||song.images[current.page].ratio||1);r.crop=c;r.cropNeedsReview=false;return next})())}}/></label>})}<footer><button className="quiet-danger" style={{marginRight:'auto'}} onClick={()=>setConfirmDeleteRow(true)}>删除本行</button><button onClick={()=>commit((()=>{const next=structuredClone(doc);next.rows[cursor.row].crop=structuredClone(initial.rows[cursor.row].crop);next.rows[cursor.row].cropNeedsReview=initial.rows[cursor.row].cropNeedsReview;return next})())}>恢复裁切</button><button className="primary" onClick={()=>{commit((()=>{const next=structuredClone(doc);next.rows[cursor.row].cropNeedsReview=false;if(next.rows[cursor.row].crop?.version>=2)next.rows[cursor.row].crop.reviewed=true;return next})());close()}}>完成</button></footer></>}</>:<><p>右手切换音符，左手修改节奏。</p><dl><dt>← →</dt><dd>切换相邻音符，行尾自动跨行</dd><dt>↑ ↓ / 滚轮</dt><dd>切换到相邻行的第一个音</dd><dt>1 — 5</dt><dd>十六分、八分、四分、二分、全音符</dd><dt>Q / W / E / D</dt><dd>附点 / 连接 / 结束小节 / 变拍</dd><dt>连接编辑</dt><dd>方向键移动终点，Enter 确认，Esc 取消；选中连接后 Delete 删除</dd><dt>R / F</dt><dd>升 / 降八度，限定低中高三个音区</dd></dl><p className="hint">点击原谱可自由浏览。快捷键在右侧修正区域生效。保存后会更新当前歌曲的训练乐谱。</p><footer><button className="primary" onClick={close}>知道了</button></footer></>}
</section></div>}
</div>}
