export const RECOVERY_TTL=24*60*60*1000;
export const validBackups=(items=[],now=Date.now())=>items.filter(i=>i.expiresAt>now);
export async function imageBytes(image){const response=await fetch(image.src);if(!response.ok)throw Error('无法读取图片原文件');return new Uint8Array(await response.arrayBuffer());}
export async function fingerprint(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');}
export function equalBytes(a,b){return a.length===b.length&&a.every((v,i)=>v===b[i]);}
export async function snapshotImage(image){const bytes=await imageBytes(image),hash=await fingerprint(bytes);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {...structuredClone(image),src:'data:'+(image.src.startsWith('data:image/')?image.src.split(';')[0].slice(5):'image/jpeg')+';base64,'+btoa(binary),hash,jobToken:null,byteLength:bytes.length,status:image.status==='processing'?'pending':image.status};}
export async function matchingBackups(image,backups,now=Date.now()){const bytes=await imageBytes(image),hash=await fingerprint(bytes);const matches=[];for(const entry of validBackups(backups,now)){if(entry.image.hash!==hash||entry.image.byteLength!==bytes.length)continue;if(equalBytes(bytes,await imageBytes(entry.image)))matches.push(entry);}return matches.sort((a,b)=>b.deletedAt-a.deletedAt);}
export function restoreBackup(entry,now=Date.now()){if(entry.expiresAt<=now)throw Error('上次结果已超过 24 小时，请重新识别');return {...structuredClone(entry.image),recoveryExpiresAt:entry.expiresAt};}
export function reconcilePractice(oldNotes,newNotes,cursor,range){const ids=new Map(newNotes.map((n,i)=>[n.id,i]));let next=ids.get(oldNotes[cursor]?.id);if(next===undefined){const after=oldNotes.slice(cursor+1).find(n=>ids.has(n.id));const before=oldNotes.slice(0,cursor).reverse().find(n=>ids.has(n.id));next=ids.get((after||before)?.id)??0;}let nextRange=null;if(range){const selected=oldNotes.slice(range.startIndex,range.endIndex+1).map(n=>ids.get(n.id));if(selected.length&&selected.every((v,i)=>v!==undefined&&v===selected[0]+i))nextRange={startIndex:selected[0],endIndex:selected.at(-1)};}return {cursor:next,range:nextRange,invalidated:!!range&&!nextRange};}
export function documentFromImages(base,images){const rows=images.flatMap((image,page)=>(image.result?.rows||[]).map(row=>({...structuredClone(row),page,imageId:image.id,src:image.src})));const structureDiagnostics=Array.isArray(base?.structureDiagnostics)?[...base.structureDiagnostics]:[];for(let i=0;i<rows.length;i++){const row=rows[i],next=rows[i+1];if(row.notes.length&&(!next||next.originalRow!==row.originalRow+1||next.origin!==row.origin)){row.notes.at(-1).annotation.tieToNext=false;if(next&&row.notes.at(-1).annotation.originalTie)row.seamNeedsReview=true;const fromNoteId=row.notes.at(-1)?.id,toNoteId=next?.notes?.[0]?.id;if(fromNoteId&&toNoteId&&next){structureDiagnostics.push({code:'SEAM_RELATION_CHANGED',severity:'warning',message:'页序变化导致相邻关系不再可靠，跨缝连接未被重新绑定',rowIndex:i,fromNoteId,toNoteId});}}}return {...base,rows,structureDiagnostics};}
